site_name: GameFlow Connect
repo_name: GitHub - GameFlow Connect
repo_url: https://github.com/Germano123/python-gameflowconnect
edit_uri: edit/main/documentation/

theme:
  name: material
  # logo: assets/logo.png
  # favicon: assets/favicon.ico
  palette:
    primary: "teal"
    accent: "cyan"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  language: "en"
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - content.action.edit
    - header.autohide
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/geh_m_gomes/
      name: instagram
    - icon: fontawesome/brands/github
      link: https://github.com/Germano123
      name: github
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Portuguese (Brasil)
      link: /ptbr/
      lang: pt-BR

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Usage Guide: getting_started/usage.md
  - Features:
      - Core Features: features/core_features.md
      - Secondary Features: features/secondary_features.md
  - Technical Details:
      - Architecture: technical_details/architecture.md
      - UI Design: technical_details/ui_design.md
      - Integrations: technical_details/integrations.md
  - Collaboration:
      - Contributing Guide: collaboration/contributing.md
      - Roadmap: collaboration/roadmap.md
      - Changelog: collaboration/changelog.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2025 - Germano Gomes